version: '3'
services:
  mongodb:
    image: mongo:4.0.8
    ports:
      - "27017:27017"
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodbuser
      MONGO_INITDB_ROOT_PASSWORD: mongoPassword
      MONGO_INITDB_DATABASE: comments
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null

  mongo-seed:
    build: ./mongo_seed
    ports:
      - "80:80"
    links:
      - mongodb





